# Generated by Django 5.2.6 on 2026-06-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('waiter', 'Waiter'), ('admin', 'Admin')], default='customer', max_length=15),
        ),
    ]
