# Generated by Django 5.2.6 on 2026-06-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('waiter', 'Waiter'), ('admin', 'Admin'), ('manager', 'Manager')], default='customer', max_length=15),
        ),
    ]
