# Generated by Django 5.2.6 on 2026-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_Read',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
