# Generated by Django 5.2.6 on 2026-06-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_Read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
    ]
