# Generated by Django 5.2.6 on 2026-06-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read_by',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_Read',
            field=models.BooleanField(default=False),
        ),
    ]
