# Generated by Django 5.2.6 on 2026-06-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservations_email_reservations_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
