# Generated by Django 5.2.6 on 2025-09-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_food_added_by_alter_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('MEAL', 'Meal'), ('DRINK', 'Drink'), ('DESSERT', 'Dessert')], max_length=50),
        ),
    ]
