# Generated by Django 5.2.6 on 2025-09-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Meal', 'Meal'), ('Drink', 'Drink'), ('Dessert', 'Dessert')], max_length=50),
        ),
    ]
