# Generated by Django 5.2.6 on 2025-09-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Ovqat', 'Ovqat'), ('Ichimlik', 'Ichimlik'), ('Shirinlik', 'Shirinlik'), ('Dengiz taomi', 'Dengiz taomi')], max_length=50),
        ),
    ]
