# Generated by Django 5.2.6 on 2025-10-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Ovqat', 'Ovqat'), ('Ichimlik', 'Ichimlik'), ('Shirinlik', 'Shirinlik'), ('Dengiz taomi', 'Dengiz taomi'), ('Salad', 'Salad'), ('Parhezbop ovqat', 'Parhezbop ovqat')], max_length=50),
        ),
    ]
