# Generated by Django 5.2.6 on 2025-10-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
