# Generated by Django 5.2.6 on 2025-10-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Meal', 'Meal'), ('Drink', 'Drink'), ('Dessert', 'Dessert'), ('Seafood', 'Seafood'), ('Salads', 'Salads'), ('Healthy food', 'Healthy food'), ('Vegetarian', 'Vegetarian'), ('Icecream', 'Icecream'), ('FastFood', 'FastFood')], max_length=50),
        ),
    ]
